Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "Target01"
  config.vm.provision "ansible", playbook: "ubuntu.yml"
  config.vm.network "private_network", ip: "192.168.50.101"
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
  end
end
