Vagrant.configure("2") do |config|
  config.vm.box = "ansible/tower"
  config.vm.hostname = "Tower"
  config.vm.network "private_network", ip: "192.168.50.103"
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
  end
end